### PR TITLE
Added bulk import/export

### PR DESCRIPTION
**Pull request by mcintyre321**
I added a bulk import/export tracks (so I could move code from NTSC to PAL carts more easily), also updated the .NET version. 

To use the import feature, a folder needs to contain track files named `{trackNo:int} - {trackName}.smkc` from 1 to 24 e.g.

```
1- Mario Circuit 1.smkc
...
24- Battle Course 4.smkc
```

### CODE REVIEW

**Comment by mcintyre321** [comment]
While I've got you attention, you don't happen to know if I need to adjust the speed settings down when moving tracks from NTSC to PAL in order to make up for the speed difference? 

I'm finding Mariokart 20XX very difficult on PAL, maybe it's meant to be that hard though!

**Comment by thomasgoldstein** [comment]
Hi! Thanks for this patch. Very sorry, I never noticed the pull request until now. I thought I'd receive a mail or something...

I actually kept the .NET version at 2.0 on purpose, to stay as compatible as possible with older .NET / 
Mono installations, and because I don't really need or use the features above 2.0 in Epic Edit. I know IDEs like Visual Studio encourage you to increase the .NET version, but is there actually a point for users as far as Epic Edit is concerned? I didn't think so, so I didn't do it.

Besides, if we really wanted to update to 4.0, then we'd better do it in a separate patch, not mixed with a new feature. It's just a good dev habit. This makes it easier to review the actual changes (here, the new feature), and also makes it possible to easily rollback just one of the changes.

Anyway, I'll have a closer look at your changes and report back.

**Comment by thomasgoldstein** [comment]
Hey. I've had a good look at your patch. Overall it is fine, but I still changed it here and there to my liking (renaming and moving stuff around), and removed unnecessary things (the .NET upgrade, the reformatting of TrackEditor, the fact you turned TrackEditor.track into a public property, etc).

I appreciate the fact you bothered making those new icons (which I still tweaked a tiny bit for consistency). I see you made all of the menu icons bigger, which is weird (and that I reverted). Was that intentional?

By the way, from a user point of view, the only thing that bothers me is the way the import all works. Export all seems to invite the user to change the file pattern if he wants to, but import all still expects each file to start with a number, and only asks the user to pick a single file. I'll see if I can do something about that later.

Changeset: https://github.com/thomasgoldstein/epicedit/commit/8d3ce314ecaa1db1cdc97f46c851866089789ed5

**Comment by mcintyre321** [comment]
I was just trying to rebuild various NTSC SMK mods for a PAL console, and that was the quickest way to code it. I thought I'd send the changes back in case you wanted them, but I appreciate the UX isn't great. No worries if you choose not to integrate them, thanks for making such a neat tool.

**Comment by thomasgoldstein** [comment]
They're already integrated. :) I'll release a new Epic Edit version with them next month. Thanks again.

**Pull request closed without merging**
